name: Deploy Network

on:
  workflow_dispatch:
    inputs:
      cloud:
        type: choice
        options: [azure, aws]
      environment:
        type: choice
        options: [dev, qa, prod]

jobs:
  deploy:
    uses: ./.github/workflows/terraform-reusable.yml
    with:
      cloud: ${{ inputs.cloud }}
      environment: ${{ inputs.environment }}
