name: Deploy Network

on:
  workflow_dispatch:
    inputs:
      cloud:
        type: choice
        options: [azure]
      environment:
        type: choice
        options: [prod]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/terraform-reusable.yml
    secrets: inherit        # 🔴 THIS IS THE FIX
    with:
      cloud: ${{ inputs.cloud }}
      environment: ${{ inputs.environment }}
