name: Deploy Network

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      cloud:
        type: choice
        options: [azure]
        default: azure
      environment:
        type: choice
        options: [dev]
        default: dev
      action:
        description: "Terraform action"
        type: choice
        options: [apply]
        default: apply

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/terraform-reusable.yml
    secrets: inherit
    with:
      cloud: azure
      environment: dev
      action: ${{ github.event.inputs.action || 'apply' }}
