name: Deploy Network

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      cloud:
        type: choice
        options: [azure]
        default: azure
      environment:
        type: choice
        options: [prod]
        default: prod

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/terraform-reusable.yml
    secrets: inherit
    with:
      # On push → fixed values
      cloud: azure
      environment: prod
